name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust to 'main' if your default branch is 'main...'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Set Git config
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Generate static files
        run: npm run generate  # Ensure this generates files in 'dist'

      - name: Deploy to GitHub Pages
        run: |
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin `gh-pages`  # Push to 'gh-pages' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
