name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Adjust to 'main' if your default branch is 'main'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set Git config
        run: |
          git config --global user.email "adamselectro@gmail.com"
          git config --global user.name "Adam Struth"

      - name: Generate static files
        run: npm run generate  # Ensure this generates files in 'dist'

      - name: Deploy to GitHub Pages
        run: |
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard origin/gh-pages
          cp -r dist/* .
          git add -A
          git
